apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html
spec:
  containers:
    - name: index-html
      data:
        index.html:
        <html>
        
        <h1>Welcome</h1>
        </br>
        <body>
                    <h2>Created custom page to run as a pod </h2>
        </body>
        </html 
  
# 2. Create a custom html page containerise it and run as a pod 
